spring:
  security:
    user-details:
      extraRU : "Lid3NgLYGrEBbrAEvES5S,USER,enabled"
      exampleRestUser : "Pov3NgLYGrEBbrAEvES5S,USER,enabled"

THING_NAME: thingName
THING_JDBC_URL: thingJdbcUrl
THING_LOGIN: thingLogin
THING_PASSWORD: thingPassword
some:
  prop:
    data: dataValue
